org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1
mixin_version=0.8.5
mod_id=dim_coord_ratio
mod_name=Dimensional Coordinates Ratio
mod_license=GPL-3.0 Only
mod_version=1.0.0
mod_group_id=com.gencal.dim_coord_ratio
mod_authors=Gencal
mod_description=Changes ratio between coordinates of all dimensions to be 1 to 1
